// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function AutoDetectSourceRoot(arg1:boolean,arg2:boolean):Promise<string>;

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function CheckInstallDirConflict(arg1:string):Promise<main.InstallDirConflict>;

export function CheckOkidociDB(arg1:string):Promise<main.OkidociCheckResult>;

export function CheckPgInstalled():Promise<main.PgCheckResult>;

export function DomReady(arg1:context.Context):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetServerInfo(arg1:string,arg2:string):Promise<main.ServerInfoDTO>;

export function GetServerStatus(arg1:string):Promise<main.ServerStatusDTO>;

export function GetUIMode():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InstallPostgresFromUsb():Promise<void>;

export function LaunchClient(arg1:string):Promise<void>;

export function PickFolder():Promise<string>;

export function PickPgDir():Promise<string>;

export function PickSqlFile():Promise<string>;

export function ResetPostgresPassword(arg1:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartInstall(arg1:main.StartInstallOptions):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function Uninstall(arg1:main.UninstallOptions):Promise<void>;

export function VerifyPostgresPassword(arg1:string):Promise<void>;
