// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectSourceRoot(arg1, arg2) {
  return window['go']['main']['App']['AutoDetectSourceRoot'](arg1, arg2);
}

export function BeforeClose(arg1) {
  return window['go']['main']['App']['BeforeClose'](arg1);
}

export function CheckInstallDirConflict(arg1) {
  return window['go']['main']['App']['CheckInstallDirConflict'](arg1);
}

export function CheckOkidociDB(arg1) {
  return window['go']['main']['App']['CheckOkidociDB'](arg1);
}

export function CheckPgInstalled() {
  return window['go']['main']['App']['CheckPgInstalled']();
}

export function DomReady(arg1) {
  return window['go']['main']['App']['DomReady'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetServerInfo(arg1, arg2) {
  return window['go']['main']['App']['GetServerInfo'](arg1, arg2);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetUIMode() {
  return window['go']['main']['App']['GetUIMode']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPostgresFromUsb() {
  return window['go']['main']['App']['InstallPostgresFromUsb']();
}

export function LaunchClient() {
  return window['go']['main']['App']['LaunchClient']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickPgDir() {
  return window['go']['main']['App']['PickPgDir']();
}

export function PickSqlFile() {
  return window['go']['main']['App']['PickSqlFile']();
}

export function ResetPostgresPassword(arg1) {
  return window['go']['main']['App']['ResetPostgresPassword'](arg1);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartInstall(arg1) {
  return window['go']['main']['App']['StartInstall'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function VerifyPostgresPassword(arg1) {
  return window['go']['main']['App']['VerifyPostgresPassword'](arg1);
}
