// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {context} from '../models';

export function AutoDetectSourceRoot(arg1:boolean,arg2:boolean):Promise<string>;

export function BackupServerDatabase(arg1:string):Promise<main.DatabaseBackupResultDTO>;

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function CancelInstall():Promise<void>;

export function CheckDbInstalled():Promise<main.DbCheckResult>;

export function CheckInstallDirConflict(arg1:string):Promise<main.InstallDirConflict>;

export function CheckInternet():Promise<boolean>;

export function CheckNextcloudServerUpdate(arg1:string,arg2:string,arg3:string):Promise<main.NextcloudUpdateCheckDTO>;

export function CheckNextcloudServerUpdateWithSaved(arg1:string):Promise<main.NextcloudUpdateCheckDTO>;

export function CheckOkidociDB(arg1:string,arg2:string):Promise<main.OkidociCheckResult>;

export function DisconnectAllServerUsers(arg1:string):Promise<void>;

export function DisconnectServerUser(arg1:string,arg2:number):Promise<void>;

export function DomReady(arg1:context.Context):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetNextcloudSavedLogin():Promise<string>;

export function GetServerInfo(arg1:string,arg2:string):Promise<main.ServerInfoDTO>;

export function GetServerStatus(arg1:string):Promise<main.ServerStatusDTO>;

export function GetServerUpdateTarget(arg1:string):Promise<main.ServerUpdateTargetDTO>;

export function GetUIMode():Promise<string>;

export function GetUpdateSourceConfig():Promise<main.UpdateSourceConfigDTO>;

export function Greet(arg1:string):Promise<string>;

export function InstallPostgresFromUsb():Promise<void>;

export function InstallPostgresInstaller(arg1:string):Promise<void>;

export function LaunchClient(arg1:string):Promise<void>;

export function ListPostgresInstallers(arg1:string):Promise<Array<main.PostgresInstallerDTO>>;

export function PickDbDir():Promise<string>;

export function PickFolder():Promise<string>;

export function PickSqlFile():Promise<string>;

export function PickUpdateArchive():Promise<string>;

export function PickUpdateFolder():Promise<string>;

export function PreviewInstallDone():Promise<boolean>;

export function ResetPostgresPassword(arg1:string,arg2:string):Promise<void>;

export function RestartServer(arg1:string):Promise<void>;

export function RevealPathInExplorer(arg1:string):Promise<void>;

export function RunServerUpdateFromNextcloud(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:boolean):Promise<main.ServerUpdateResultDTO>;

export function RunServerUpdateFromNextcloudSaved(arg1:string,arg2:boolean):Promise<main.ServerUpdateResultDTO>;

export function RunServerUpdateFromPath(arg1:string,arg2:string,arg3:boolean):Promise<main.ServerUpdateResultDTO>;

export function SaveNextcloudCredentials(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SelectDbEngine(arg1:string):Promise<void>;

export function SelectDbEngineBin(arg1:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartInstall(arg1:main.StartInstallOptions):Promise<void>;

export function StartServer(arg1:string):Promise<void>;

export function StopServer(arg1:string):Promise<void>;

export function Uninstall(arg1:main.UninstallOptions):Promise<void>;

export function ValidateSourceRoot(arg1:string,arg2:boolean,arg3:boolean):Promise<main.SourceValidationResult>;

export function ValidateSqlBackupPath(arg1:string):Promise<void>;

export function VerifyPostgresPassword(arg1:string,arg2:string):Promise<void>;
