// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoDetectSourceRoot(arg1, arg2) {
  return window['go']['main']['App']['AutoDetectSourceRoot'](arg1, arg2);
}

export function BeforeClose(arg1) {
  return window['go']['main']['App']['BeforeClose'](arg1);
}

export function CancelInstall() {
  return window['go']['main']['App']['CancelInstall']();
}

export function CheckDbInstalled() {
  return window['go']['main']['App']['CheckDbInstalled']();
}

export function CheckInstallDirConflict(arg1) {
  return window['go']['main']['App']['CheckInstallDirConflict'](arg1);
}

export function CheckOkidociDB(arg1, arg2) {
  return window['go']['main']['App']['CheckOkidociDB'](arg1, arg2);
}

export function DomReady(arg1) {
  return window['go']['main']['App']['DomReady'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetServerInfo(arg1, arg2) {
  return window['go']['main']['App']['GetServerInfo'](arg1, arg2);
}

export function GetServerStatus(arg1) {
  return window['go']['main']['App']['GetServerStatus'](arg1);
}

export function GetUIMode() {
  return window['go']['main']['App']['GetUIMode']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InstallPostgresFromUsb() {
  return window['go']['main']['App']['InstallPostgresFromUsb']();
}

export function InstallPostgresInstaller(arg1) {
  return window['go']['main']['App']['InstallPostgresInstaller'](arg1);
}

export function LaunchClient(arg1) {
  return window['go']['main']['App']['LaunchClient'](arg1);
}

export function ListPostgresInstallers(arg1) {
  return window['go']['main']['App']['ListPostgresInstallers'](arg1);
}

export function PickDbDir() {
  return window['go']['main']['App']['PickDbDir']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickSqlFile() {
  return window['go']['main']['App']['PickSqlFile']();
}

export function PreviewInstallDone() {
  return window['go']['main']['App']['PreviewInstallDone']();
}

export function ResetPostgresPassword(arg1, arg2) {
  return window['go']['main']['App']['ResetPostgresPassword'](arg1, arg2);
}

export function RestartServer(arg1) {
  return window['go']['main']['App']['RestartServer'](arg1);
}

export function SelectDbEngine(arg1) {
  return window['go']['main']['App']['SelectDbEngine'](arg1);
}

export function SelectDbEngineBin(arg1) {
  return window['go']['main']['App']['SelectDbEngineBin'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}

export function StartInstall(arg1) {
  return window['go']['main']['App']['StartInstall'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer(arg1) {
  return window['go']['main']['App']['StopServer'](arg1);
}

export function Uninstall(arg1) {
  return window['go']['main']['App']['Uninstall'](arg1);
}

export function ValidateSourceRoot(arg1, arg2, arg3) {
  return window['go']['main']['App']['ValidateSourceRoot'](arg1, arg2, arg3);
}

export function ValidateSqlBackupPath(arg1) {
  return window['go']['main']['App']['ValidateSqlBackupPath'](arg1);
}

export function VerifyPostgresPassword(arg1, arg2) {
  return window['go']['main']['App']['VerifyPostgresPassword'](arg1, arg2);
}
